.TH coccigrep 1 "October 16, 2011" "version 1.3"
.SH NAME
coccigrep - semantic grep for the C programming language

.SH SYNOPSIS
.B coccigrep
.RI [ OPTIONS ]
.BI "\-t " "TYPE "
.RI [ FILE .\|.\|.]

.SH DESCRIPTION
.BR coccigrep " is a semantic " grep " for the C programming language."
.RB "It is based on " coccinelle " and can be used to find where a given"
.RB "structure is used in C source files. " coccigrep " depends"
.RB "on the " spatch " program which comes with coccinelle."

.SH OPTIONS
.SS Display options
.TP
.BI \-A " NUM" "\fR,\fP \-\^\-after\-context=" NUM
.RI "Print " NUM " lines of trailing context after matching line."
.TP
.BI \-B " NUM" "\fR,\fP \-\^\-before\-context=" NUM
.RI "Print " NUM " lines of leading context before matching line."
.TP
.BR \-c ", " \-\-color
Colorize output (needs pygments).
.TP
.BI \-C " NUM" "\fR,\fP \-\^\-context=" NUM
.RI "Print " NUM " lines of output context."
.TP
.BI \-f " FORMAT" "\fR,\fP \-\^\-output-format=" FORMAT
Colorize format for output.
.I FORMAT
.RB "is " term " or " html .

.SS Search options
.TP
.BI \-a " ATTRIBUTE" "\fR,\fP \-\^\-attribut=" ATTRIBUTE
.RI "Match operations that involve the field " ATTRIBUTE " of the"
.RB "structure given with option " \-t "."
.TP
.B \-\-cpp
Activate coccinelle C++ support.
.TP
.BI \-o " OPERATION" "\fR,\fP \-\^\-operation=" OPERATION
Specify the kind of operation to look for.
.RI "The available values for " OPERATION " are:"

.RS
.B deref
.RS
.RI "Any access to an " ATTRIBUTE .
.RE
.B func
.RS
.RI "Any function call for which one of the parameters is of type " TYPE
.RB "(as defined with " \-t "). In this operation, the option " \-a " sets"
the name of the function to match and does not refer to an attribute.
.RE
.B set
.RS
.RI "Any operation wich changes the value of an " ATTRIBUTE .
.RE
.B test
.RS
.RI "Any boolean test where an " ATTRIBUTE " appears."
.RE
.B used
.RS
.RI "Any statement where the type " TYPE " (as defined with"
.BR \-t ") appears."
.RI "This " OPERATION " does not need to look for an " ATTRIBUTE " thus"
.RB "it ignores option " \-a .
.RE

.RB "The default operation is " used " if " \-a " is not given,"
.RB "or " deref " if it is."
.RI "Depending on your environment, more " OPERATION "s may be available."
.RB "See option " \-L " for information about"
.IR OPERATION " listing."
.RE
.TP
.BI \-t " TYPE" "\fR,\fP \-\^\-type=" TYPE
C type to look for.

.SS Editor options
.TP
.BR \-E ", " \-\-emacs
Emacs output.
.TP
.BR \-V ", " \-\-vim
Vim output.

.SS Program information
.TP
.BR \-h ", " \-\-help
Print usage message and exit.
.TP
.BR \-L ", " \-\-list-operations
.RI "List available " OPERATION "s. Use together with"
.BR \-v " to get detailed information about listed"
.IR OPERATION "s."
.TP
.BR \-v ", " \-\-verbose
Verbose output (including coccinelle errors).
.TP
.B \-\-version
.RB "Print the version number of " coccigrep "."

.SS Other options
.TP
.BI \-p " NCPUS" "\fR,\fP \-\^\-process=" NCPUS
Number of cpus to use.
.TP
.BI \-s " SP" "\fR,\fP \-\^\-sp=" SP
Semantic patch to use.
.TP
.BI \-l " FILE" "\fR,\fP \-\^\-file\-list=" FILE
File containing a list of input files.

.SH BUGS
The operation option could lead to some missed match because the semantic
patches used internally may need some improvements.
.RB "Use options " \-L " together with " \-v " to get detailed information"
about available operations.

.RB "Please report issues to <" https://github.com/regit/coccigrep/issues ">."
All ideas are welcome.

.SH EXAMPLES
.nf
.RB "1. Find where in a set of files the structure " Packet " is used:"
	$ coccigrep -t Packet *c

.nf
.RB "2. Finds where in a set of files the " datalink " attribute is used in the structure " Packet ":"
	$ coccigrep -t Packet -a datalink *c

.nf
.RB "3. Finds where the " datalink " attribute of " Packet " is set:"
	$ coccigrep -t Packet -a datalink -o set source*c

.SH FILES
.IR ~/.coccigrep "\tConfiguration file for coccigrep."

.SH SEE ALSO
spatch(1)

.RB "Project homepage: <" http://home.regit.org/software/coccigrep/ ">"
